### ISSUE TITLE
license: sort out licensing

### ISSUE THREAD

**Issue by cyphar** [cyphar/umoci#35]
I really would like to license this project under `GPLv3+`, but currently the `image/` code needs to be Apache licensed if we want to have any hope of the code being merged into the OCI. We could do some sort of dual-licensing thing, but I feel like that wouldn't end well.

**Comment by jawnsy** [comment]
Hey Aleksa,

What are your goals for this project?  If you're looking for adoption/usage, a permissive license like Apache is ideal (especially because, as you note, it's the same license used by OCI, Kubernetes, Docker, and much of the container ecosystem today).

On the other hand, I can understand the desire to have people contribute back to your project; a copyleft license encourages collaboration on the original project.  There are a few prominent GPL-licensed codebases that were way better than their BSD counterparts (things like coreutils), so there's something to be said for that as well.

I'd like to suggest the idea that people who want to contribute will do so, regardless of license. Even with a copyleft license, people that don't want to contribute will likely just look for a different project instead. Red Hat contributes back to the community because it's "the right thing to do", but even excluding the moral/ethical argument, it's just the smart thing to do: not contributing back means you'll likely have to deal with messy merge conflicts later down the road.

But whichever way you go, I would recommend against dual-licensing, just because it makes things confusing (and risky for enterprise developers - there might be a general "Apache is OK" sentiment, but things get murky with any non-standard arrangement, especially since `GPL` is a dirty word in many organizations).

Good luck! I know choosing a license is really tough :smile:

Cheers,

Jonathan

**Comment by cyphar** [comment]
> What are your goals for this project? If you're looking for adoption/usage, a permissive license like Apache is ideal (especially because, as you note, it's the same license used by OCI, Kubernetes, Docker, and much of the container ecosystem today).

Which makes me sad :cry:. But the main reason why it is currently Apache licensed is that I'm hoping that (at the very least) the packages under `oci/**` will eventually become part of the OCI `image-tools` repository so that I don't need to maintain it forever.

> On the other hand, I can understand the desire to have people contribute back to your project; a copyleft license encourages collaboration on the original project.

That's not really my main reason for using copyleft. I personally strongly believe that permissive licensing is dangerous to free software, because it allows for proprietary forks to fracture the userbase. Now, that doesn't stop me from contributing to the OCI (obviously) but when discussing licensing my own projects, I have to think about it a lot more.

If I didn't intend for `oci/**` to be merged into the actual OCI I would probably just go with GPLv3. It's what a lot of openSUSE and SUSE projects use, and also what I personally feel is the best license for free software.

> Red Hat contributes back to the community because it's "the right thing to do"

So does SUSE. :wink:
